using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text.Json;

namespace Kiln.Plugins.Packaging {
	public static class PackageModRunner {
		public static PackageModResult Run(string outputDir) {
			if (string.IsNullOrWhiteSpace(outputDir))
				throw new ArgumentException("outputDir is required", nameof(outputDir));

			Directory.CreateDirectory(outputDir);

			var manifestPath = Path.Combine(outputDir, "manifest.json");
			var installPath = Path.Combine(outputDir, "install.md");
			var rollbackPath = Path.Combine(outputDir, "rollback.ps1");
			var packagePath = Path.Combine(outputDir, $"{Path.GetFileName(outputDir)}.zip");

			var payloadFiles = EnumeratePayloadFiles(outputDir, new[] {
				"manifest.json",
				"install.md",
				"rollback.ps1",
				Path.GetFileName(packagePath),
			});

			File.WriteAllText(manifestPath, BuildManifest(outputDir, payloadFiles));
			File.WriteAllText(installPath, BuildInstallDoc());
			File.WriteAllText(rollbackPath, BuildRollbackScript());

			if (File.Exists(packagePath))
				File.Delete(packagePath);
			ZipFile.CreateFromDirectory(outputDir, packagePath, CompressionLevel.Optimal, false);

			return new PackageModResult(outputDir, manifestPath, installPath, rollbackPath, packagePath, payloadFiles);
		}

		static List<string> EnumeratePayloadFiles(string root, IReadOnlyList<string> excludeNames) {
			var list = new List<string>();
			foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)) {
				var name = Path.GetFileName(file);
				if (IsExcluded(name, excludeNames))
					continue;
				list.Add(Path.GetRelativePath(root, file));
			}
			return list;
		}

		static bool IsExcluded(string name, IReadOnlyList<string> excludeNames) {
			for (var i = 0; i < excludeNames.Count; i++) {
				if (string.Equals(name, excludeNames[i], StringComparison.OrdinalIgnoreCase))
					return true;
			}
			return false;
		}

		static string BuildManifest(string outputDir, IReadOnlyList<string> payloadFiles) {
			var manifest = new {
				name = Path.GetFileName(outputDir),
				version = "0.1.0",
				generatedUtc = DateTime.UtcNow,
				files = payloadFiles,
			};
			return JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });
		}

		static string BuildInstallDoc() {
			return @"# Install

1) Copy all files in this package to your mod folder or game directory.
2) Keep manifest.json and rollback.ps1 for uninstall.

## Notes
- This package is generated by Kiln.
- Files listed in manifest.json are the payload items.";
		}

		static string BuildRollbackScript() {
			return @"param(
	[string]$InstallRoot = (Get-Location).Path
)

$manifest = Join-Path $PSScriptRoot ""manifest.json""
if (-not (Test-Path $manifest)) {
	Write-Error ""manifest.json not found.""
	exit 1
}

$data = Get-Content $manifest -Raw | ConvertFrom-Json
foreach ($file in $data.files) {
	$target = Join-Path $InstallRoot $file
	if (Test-Path $target) {
		Remove-Item $target -Force -ErrorAction SilentlyContinue
	}
}";
		}
	}
}
